[package]
name = "ha-cli-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.0"
base64 = "0.13.0"
dirs = "4.0.0"
reqwest = { version = "0.11.10", features = ["blocking"] }